site_name: RuheIT Docs
theme:
  palette:
    scheme: default
logo: assets/logo.png
favicon: assets/logo.png
nav:
    - Home: index.md
    - Team: team.md
    - Infraestructura: infra.md
    - Tools: tools.md
    - Microsoft 365: microsoft365.md
