site_name: RuheIT Docs
theme: material
logo: assets/logo.png
favicon: assets/logo.png
palette:
    primary: green
nav:
    - Home: index.md
    - Team: team.md
    - Infraestructura: infra.md
    - Tools: tools.md
    - Microsoft 365: microsoft365.md
