site_name: RuheIT Docs
theme:
  name: material
  font:
    text: Roboto
  language: es
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Activa el modo oscuro
      primary: green
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle: 
        icon: material/toggle-switch
        name: Activa el modo claro
      primary: green
  logo: assets/logo.png
  favicon: assets/logo.png
nav:
    - Home: index.md
    - Equipo: equipo.md
    - Memoria: memoria.md
    - Empresa:
      - Práctica 1: empresa/practica1.md
      - Práctica 2: empresa/practica2.md
      - Práctica 3: empresa/practica3.md
      - Práctica 4: empresa/practica4.md
      - Práctica 5: empresa/practica5.md
      - Práctica 6: empresa/practica6.md
      - Práctica 7: empresa/practica7.md
      - Práctica 8: empresa/practica8.md
    - Infraestructura: infra.md
    - Herramientas: herramientas.md
    - Microsoft 365 y Azure: microsoft365.md
    - Crypto: crypto.md
    - Aplicaciones:
      - GoPhish: aplicaciones/gophish.md
      - Grafana: aplicaciones/grafana.md
      - Mailcow: aplicaciones/mailcow.md
      - Nessus: aplicaciones/nessus.md
      - Portainer: aplicaciones/portainer.md
      - CodiMD: aplicaciones/codimd.md
      - Moodle: aplicaciones/moodle.md
      - Pritunl: aplicaciones/pritunl.md
      - PwnDoc: aplicaciones/pwndoc.md
      - Vault: aplicaciones/vault.md
      - Zabbix: aplicaciones/zabbix.md
    - Servicios:
      - Auditoría de sistemas (interna): servicios/auditsistemas.md
      - Auditorías de redes inalámbricas: servicios/auditoriainalambricas.md
      - Auditorías de infraestructura web: servicios/auditweb.md
      - Campañas de phising, awareness: servicios/phishingawareness.md
      - Gestión de infraestructura: servicios/gestioninfra.md
      - Monitorización de servidores y servicios: servicios/monitoring.md
      - eLearning: servicios/eLearning.md
      - CTF: servicios/ctf.md
      - Correo y colaboración: servicios/emailandcolab.md
      - VDI: servicios/vdi.md
      - Web hosting: servicios/webhosting.md
    - Seguridad: 
      - Auditoría de seguridad: mitigacionesSeguridad/auditoria.md
      - Mitigaciones realizadas:
        - XMLRPC en WordPress: mitigacionesSeguridad/mitigationXmlrpc.md
        - PkExec (PwnKit): mitigacionesSeguridad/pkexecPwnKit.md

extra:
  generator: false
  analytics:
    provider: google
    property: G-E7KR9DKYXC
    feedback:
      title: Te resultó útil esta página?
      ratings:
        - icon: material/emoticon-happy-outline
          name: Fue útil
          data: 1
          note: >-
            Gracias por tu feedback!
        - icon: material/emoticon-sad-outline
          name: Esta página podría ser mejorada.
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="ruheit.xyz" target=_blank>feedback form</a>.
markdown_extensions:
  - footnotes
  - admonition
  - abbr
  - md_in_html
  - tables
  - toc:
      title: Contenido
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
copyright: Copyright &copy; 2022 RuheIT
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js